version: '3.1'

services:
  postgres:
    image: postgres
    container_name: restdb
    environment:
      POSTGRES_USER: ctysh
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: restapi
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
volumes:
  postgres_data:
    driver: local