DROP DATABASE IF EXISTS post05;
CREATE DATABASE post05;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Userdata;

\c post05;

CREATE TABLE Users (
    ID SERIAL,
    Username VARCHAR(100) PRIMARY KEY
);

CREATE TABLE Userdata (
    UserID Int NOT NULL,
    Name VARCHAR(100),
    Surname VARCHAR(100),
    Description VARCHAR(200)
);